require "./ast"

module Adamas
  module Compiler
    module Frontend
      # The semantic origin of an owner-tagged syntax reference.
      #
      # Origin is metadata for admission and diagnostics; the owner and ExprId
      # are the identity. It must never be reconstructed from source text,
      # spans, or an arena-size heuristic.
      enum OwnedExprOrigin : UInt8
        Parsed
        MacroExpansion
      end

      # A compile-scoped, zero-copy reference to one syntax node.
      #
      # The reference retains the exact AstArena instance. A CanonicalSyntaxView
      # is retained as its dynamic AstArena subtype, so view-local ownership
      # checks remain available at the admission boundary. VirtualArena and
      # PageArena are deliberately outside this sidecar until they have an
      # owner/lifetime contract of their own.
      class OwnedExprRef
        getter arena : AstArena
        getter expr_id : ExprId
        getter origin : OwnedExprOrigin

        # Admission for parsed syntax is intentionally named so callers cannot
        # accidentally label an arbitrary in-range id as a macro result.
        def self.parsed(owner : ArenaLike, expr_id : ExprId) : self
          new(require_ast_arena(owner), expr_id, OwnedExprOrigin::Parsed)
        end

        # Runs one trusted macro producer under the exact retained owner and
        # tags its result before the bare ExprId can cross that boundary.
        # Plain AstArena has no per-node provenance ledger, so the producer must
        # use the supplied owner. CanonicalSyntaxView additionally verifies its
        # generated-id ledger. An invalid result is the normal semantic nil.
        def self.capture_macro_expansion(owner : ArenaLike, & : AstArena -> ExprId) : self?
          arena = require_ast_arena(owner)
          generated_floor = arena.size
          expr_id = yield arena
          raise ArgumentError.new("OwnedExprRef macro expansion owner shrank during capture") if arena.size < generated_floor
          return nil if expr_id.null_ptr? || expr_id.invalid?
          raise ArgumentError.new("OwnedExprRef macro expansion id precedes its owner floor") if expr_id.index < generated_floor
          raise ArgumentError.new("OwnedExprRef macro expansion id is outside its owner") if expr_id.index >= arena.size
          if view = arena.as?(CanonicalSyntaxView)
            unless view.owns_generated_id?(expr_id)
              raise ArgumentError.new("OwnedExprRef macro expansion id is not generated by its canonical owner")
            end
          end
          new(arena, expr_id, OwnedExprOrigin::MacroExpansion)
        end

        # Whether this reference is admitted by its retained owner.
        def valid? : Bool
          return false if @expr_id.null_ptr? || @expr_id.invalid?

          if @arena.is_a?(CanonicalSyntaxView)
            # `CanonicalSyntaxView` is an `AstArena` subtype. Use an explicit
            # cast after the predicate so Crystal does not resolve the
            # subtype-only ownership methods against the base class.
            view = @arena.as(CanonicalSyntaxView)
            case @origin
            when .parsed?
              view.owns_source_id?(@expr_id)
            when .macro_expansion?
              view.owns_generated_id?(@expr_id)
            else
              false
            end
          else
            index = @expr_id.index
            index >= 0 && index < @arena.size
          end
        end

        # Fetches through the retained owner only. Foreign canonical-view IDs
        # and invalid IDs return nil instead of falling back to another arena.
        def fetch? : TypedNode?
          return nil unless valid?
          if @arena.is_a?(CanonicalSyntaxView)
            @arena.as(CanonicalSyntaxView)[@expr_id]?
          else
            @arena[@expr_id]?
          end
        end

        def fetch : TypedNode
          fetch? || raise IndexError.new("OwnedExprRef is not admitted by its owner")
        end

        def same_owner?(other : OwnedExprRef) : Bool
          @arena.same?(other.arena)
        end

        private def self.require_ast_arena(owner : ArenaLike) : AstArena
          case owner
          when AstArena
            owner
          else
            raise ArgumentError.new("OwnedExprRef requires an AstArena or CanonicalSyntaxView owner")
          end
        end

        private def initialize(@arena : AstArena, @expr_id : ExprId, @origin : OwnedExprOrigin)
          validate!
        end

        private def validate! : Nil
          raise ArgumentError.new("OwnedExprRef cannot contain an invalid or null ExprId") unless valid?
        end
      end
    end
  end
end
